### ISSUE TITLE
Update README.doc for non-expert users

### ISSUE THREAD

**Issue by fermenreq** [elastest/elastest-toolbox#2]
Hi @franciscoRdiaz ,

I started to deploy elastest-toolbox and  I cant continue cause a lack of information
to run `minikube commands`. Readme section related:  [Minikube in VM](https://github.com/elastest/elastest-toolbox/tree/master/kubernetes#minikube-in-vm) 

I suggest to update README.doc  adding some points for the inexperienced users:

## Install Minikube on Linux by downloading a self-contained executable:
`curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube`

## Add  executable command to $ PATH or move it for example to `/usr/local/bin`
`sudo cp minikube /usr/local/bin && rm minikube`

## Running minikube within a VM:

**root@osboxes:/home/osboxes/Desktop/Elastest/elastest-toolbox/kubernetes/ek#** `sudo minikube start --memory=6048 --cpus=4 --extra-config=apiserver.service-node-port-range=1000-60000 --extra-config kubelet.node-ip=VM-IP --vm-driver=none`

...

Thanks,
Fernando Mendez - fernando.mendez@atos.net

**Comment by franciscoRdiaz** [comment]
Hi @fermenreq ,

I will respond in the same order as your comments.

We appreciate your comment and for this we have already updated the documentation with a small comment indicating where you can find the instructions to install Minikube and kubectl.

This guide is not intended to tell you how to set up Minikube apart from what is strictly necessary for ElasTEst.

The last comment mixes the two ways to start Minikube to deploy ElastTest. With your command you are not running Minikube on a VM. To do this you have to remove the option `--vm-driver=none` from your command.

Thanks for your comments.
